# Here is an example of YAML

PORT: 8080

DATABASE:
  HOST: 34.93.109.204
  PORT: 5432
  USER: quotes-app
  PASSWORD: Samaritan314#!$
  DB: test
  SSLMode: require
  

ServerAddress: :8080
API_SECRET: nextEraOfWesternCivilization2442
TOKEN_HOUR_LIFESPAN: 1h
