// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Quote struct {
	ID        int32            `json:"id"`
	UserID    int32            `json:"user_id"`
	Content   string           `json:"content"`
	Author    string           `json:"author"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID        int32              `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
