// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountQuotes(ctx context.Context) (int64, error)
	CreateQuote(ctx context.Context, arg CreateQuoteParams) (*Quote, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeleteQuote(ctx context.Context, id int32) (*Quote, error)
	GetAllQuotes(ctx context.Context) ([]*Quote, error)
	GetQuoteByID(ctx context.Context, id int32) (*Quote, error)
	GetQuotesByUserID(ctx context.Context, userID int32) (*Quote, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserByID(ctx context.Context, id int32) (*User, error)
	SearchQuotes(ctx context.Context, dollar_1 *string) (*Quote, error)
	UpdateQuote(ctx context.Context, arg UpdateQuoteParams) (*Quote, error)
}

var _ Querier = (*Queries)(nil)
